package com.arnis.paper;

import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * A durable record of which regions <em>arnis</em> produced.
 *
 * <p>The presence of an {@code r.X.Z.mca} proves only that the server has written
 * that region — it writes one for anything it generates, including the void it
 * generates when a player outruns streaming. Treating file presence as "baked"
 * therefore makes such a hole permanent: it looks baked forever after, and only a
 * manual {@code /arnis rebake} escapes it.
 *
 * <p>So every successful bake also drops an empty marker file in
 * {@code <world>/arnis-baked/}. A region file with no marker was generated by the
 * server, not by arnis, and can be re-baked automatically once nothing has it
 * loaded. Markers are separate files rather than one index so that concurrent bake
 * workers never contend, and a half-written index can never lose the lot.
 */
public final class BakedIndex {

    private static final String DIR = "arnis-baked";
    private static final Pattern MARKER = Pattern.compile("^r\\.(-?\\d+)\\.(-?\\d+)\\.arnis$");
    private static final Pattern REGION_FILE = Pattern.compile("^r\\.(-?\\d+)\\.(-?\\d+)\\.mca$");

    private BakedIndex() {}

    /** Whether this world has an index yet (absent for worlds predating it). */
    public static boolean exists(File worldDir) {
        return new File(worldDir, DIR).isDirectory();
    }

    /**
     * Record that arnis produced region {@code (rx, rz)}. Called from bake workers,
     * so it must be safe off the main thread — distinct files per region make it so.
     *
     * @return whether the marker is now on disk
     */
    public static boolean mark(File worldDir, int rx, int rz) {
        File dir = new File(worldDir, DIR);
        if (!dir.isDirectory() && !dir.mkdirs()) {
            return false;
        }
        File marker = new File(dir, "r." + rx + "." + rz + ".arnis");
        try {
            return marker.isFile() || marker.createNewFile();
        } catch (IOException e) {
            return false;
        }
    }

    /** The regions arnis has baked, per the marker directory. */
    public static Set<Long> marked(File worldDir) {
        return keysIn(new File(worldDir, DIR), MARKER);
    }

    /** The regions that have a region file on disk, whoever wrote it. */
    public static Set<Long> regionFiles(File worldDir) {
        return keysIn(new File(worldDir, "region"), REGION_FILE);
    }

    private static Set<Long> keysIn(File dir, Pattern pattern) {
        Set<Long> out = new HashSet<>();
        File[] files = dir.listFiles();
        if (files == null) {
            return out;
        }
        for (File f : files) {
            Matcher m = pattern.matcher(f.getName());
            if (m.matches()) {
                out.add(BakeService.key(Integer.parseInt(m.group(1)), Integer.parseInt(m.group(2))));
            }
        }
        return out;
    }
}
